### ISSUE TITLE
404 error running rapberrypi debian 12

### ISSUE THREAD

**Issue by SugaComa** [novafacile/novagallery#49]
after installing I am getting 404 error - now I think this is Apache being slightly different build for raspberrypi.

my error log says:

`PHP Fatal error:  Uncaught Error: Failed opening required 'nova-themes//index.php' (include_path='.:/usr/share/php') in /var/www/mysite.com/public_html/content/gallery/nova-base/core/Template.php:15\nStack trace:\n#0 /var/www/mysite.com/public_html/content/gallery/nova-base/app/router.php(38): Template::render()\n#1 /var/www/mysite.com/public_html/content/gallery/nova-base/core/Router.php(136): {closure}()\n#2 /var/www/mysite.com/public_html/content/gallery/nova-base/app/router.php(42): Router::run()\n#3 /var/www/mysite.com/public_html/content/gallery/nova-base/init.php(60): require('...')\n#4 /var/www/mysite.com/public_html/content/gallery/index.php(11): require_once('...')\n#5 {main}\n  thrown in /var/www/mysite.com/public_html/content/gallery/nova-base/core/Template.php on line 15`

my htaccess file is as follows

`
RewriteEngine on
RewriteBase /gallery/

# Deny direct access to the next directories
RewriteRule ^nova-config/.*$ - [R=404,L]
RewriteRule ^nova-base/.*$ - [R=404,L]
RewriteRule ^nova-languages/.*$ - [R=404,L]

# All URL process by index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*) index.php [PT,L]
# Deny direct access to the next directories
RewriteRule ^nova-config/.*$ - [R=404,L]
RewriteRule ^nova-base/.*$ - [R=404,L]
RewriteRule ^nova-languages/.*$ - [R=404,L]

# All URL process by index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*) index.php [PT,L]`

the issue I think is that the everythings needs to see files in the /var/www/mysite.com/content/gallery to function as it is a self contained environment, but raspberrypi version of apache redirect us to /usr/share/php

how can redirect it to look in the right folder path

please note this is a completely fresh instal - i am also seeing similar errors using budit

**Comment by david-novafacile** [comment]
Please try with the new release [novaGallery v2 Beta1](https://github.com/novafacile/novagallery/releases/tag/v2.0-beta1). Please note that this is currently still a beta version.
